server.port: 0
logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
spring:
  jpa:
    properties.hibernate.format-sql: true
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/explore-main
    username: vxuser
    password: vxpasswd
management:
  endpoints:
    web:
      exposure:
        include: "*"