server:
  port: 0
spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
    database: POSTGRESQL
    show-sql: true
  sql:
    init:
      mode: always
  jackson:
    serialization:
      fail-on-empty-beans: false
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/explore-request
    username: vxuser
    password: vxpasswd
logging:
  level:
    org:
      zalando.logbook: TRACE
      springframework:
        orm:
          jpa: INFO
        transaction: INFO
management:
  endpoints:
    web:
      exposure:
        include: "*"
