spring:
  cloud:
    loadbalancer:
      configurations: health-check
      retry:
        enabled: true
    gateway:
      discovery.locator.enabled: true
      actuator.verbose.enabled: false
      routes:
        - id: main_service_route
          uri: lb://MAIN-SERVICE
          predicates:
            - Path=/admin/**,/users/**,/events/**,/compilations/**,/categories/**
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true
